### ISSUE TITLE
Tutorial link broken

### ISSUE THREAD

**Issue by dorschw** [kkinder/puepy#18]
Hey, the [tutorial](https://docs.puepy.dev/tutorial.html) link in https://puepy.dev/ is broken, leading to a `404 - Not found` page.

**Comment by i3iorn** [comment]
Not sure if It's supposed to be a page. All the tutorials are nested below "https://docs.puepy.dev/tutorial/", like "https://docs.puepy.dev/tutorial/00-using-this-tutorial/". Would make sense if that was where the link was pointing.

**Comment by kkinder** [comment]
Oops, right you are. When I switched from Writerside to Mkdocs, the links changed. Sorry about that.

**Comment by kkinder** [comment]
Fixed.
